apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: avalier-demo1
  #namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avalier-demo1
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70


 