NAME: avalier-demo
LAST DEPLOYED: Sun Jun 19 23:47:13 2022
NAMESPACE: default
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
# Source: avalier-demo1/templates/hpa.yaml
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: avalier-demo-avalier-demo1
  labels:
    app: avalier-demo-avalier-demo1
    helm.sh/chart: avalier-demo1-0.1.0
    app.kubernetes.io/name: avalier-demo1
    app.kubernetes.io/instance: avalier-demo
    app.kubernetes.io/version: "latest"
    app.kubernetes.io/managed-by: Helm
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: avalier-demo-avalier-demo1
  minReplicas: 1
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

