apiVersion: v1
kind: Service
metadata:
  name: {{ include "avalier-demo1.fullname" . }}
  labels:
    app: {{ include "avalier-demo1.fullname" . }}
    {{- include "avalier-demo1.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 5000
    - name: https
      protocol: TCP
      port: 443
      targetPort: 5001
  selector:
    {{- include "avalier-demo1.selectorLabels" . | nindent 4 }}
